import 'named_group.dart';

/// The four curated Named Groups sub-lists: the 12 tribes, the 12 apostles,
/// the judges of Israel, and the major/minor prophets.
const List<NamedGroupEntry> namedGroups = [
  // --- 12 Tribes of Israel (birth order of Jacob's sons) ---
  NamedGroupEntry(
    id: 'tribe-reuben',
    list: NamedGroupList.tribes,
    name: 'Reuben',
    subtitle: "Jacob's firstborn, by Leah",
    notes: 'Lost his birthright privilege for defiling his father\'s bed.',
    citations: ['Genesis 29:32', 'Genesis 49:3-4'],
    order: 1,
  ),
  NamedGroupEntry(
    id: 'tribe-simeon',
    list: NamedGroupList.tribes,
    name: 'Simeon',
    subtitle: "Jacob's second son, by Leah",
    notes: 'Later absorbed largely into Judah\'s territory.',
    citations: ['Genesis 29:33'],
    order: 2,
  ),
  NamedGroupEntry(
    id: 'tribe-levi',
    list: NamedGroupList.tribes,
    name: 'Levi',
    subtitle: "Jacob's third son, by Leah",
    notes: 'Received no territorial inheritance; set apart as Israel\'s priestly tribe instead.',
    citations: ['Genesis 29:34', 'Numbers 18:20'],
    order: 3,
  ),
  NamedGroupEntry(
    id: 'tribe-judah',
    list: NamedGroupList.tribes,
    name: 'Judah',
    subtitle: "Jacob's fourth son, by Leah",
    notes: 'The royal tribe — David\'s line and, ultimately, the Messiah\'s.',
    citations: ['Genesis 29:35', 'Genesis 49:10'],
    order: 4,
  ),
  NamedGroupEntry(
    id: 'tribe-dan',
    list: NamedGroupList.tribes,
    name: 'Dan',
    subtitle: 'Son of Bilhah, Rachel\'s servant',
    notes: 'Samson, most famous of the judges, was of this tribe.',
    citations: ['Genesis 30:6'],
    order: 5,
  ),
  NamedGroupEntry(
    id: 'tribe-naphtali',
    list: NamedGroupList.tribes,
    name: 'Naphtali',
    subtitle: 'Son of Bilhah, Rachel\'s servant',
    notes: 'Settled in Galilee\'s hill country, later the setting for much of Jesus\' ministry.',
    citations: ['Genesis 30:8'],
    order: 6,
  ),
  NamedGroupEntry(
    id: 'tribe-gad',
    list: NamedGroupList.tribes,
    name: 'Gad',
    subtitle: 'Son of Zilpah, Leah\'s servant',
    notes: 'Settled east of the Jordan, among the first tribes to request that territory.',
    citations: ['Genesis 30:11'],
    order: 7,
  ),
  NamedGroupEntry(
    id: 'tribe-asher',
    list: NamedGroupList.tribes,
    name: 'Asher',
    subtitle: 'Son of Zilpah, Leah\'s servant',
    notes: 'Allotted fertile coastal land in the far north; blessed with abundance in Jacob\'s final words.',
    citations: ['Genesis 30:13', 'Genesis 49:20'],
    order: 8,
  ),
  NamedGroupEntry(
    id: 'tribe-issachar',
    list: NamedGroupList.tribes,
    name: 'Issachar',
    subtitle: "Jacob's ninth son, by Leah",
    notes: 'Later described as men who "understood the times," advising David.',
    citations: ['Genesis 30:18', '1 Chronicles 12:32'],
    order: 9,
  ),
  NamedGroupEntry(
    id: 'tribe-zebulun',
    list: NamedGroupList.tribes,
    name: 'Zebulun',
    subtitle: "Jacob's tenth son, by Leah",
    notes: 'Settled near the Sea of Galilee, bordering Naphtali.',
    citations: ['Genesis 30:20'],
    order: 10,
  ),
  NamedGroupEntry(
    id: 'tribe-joseph',
    list: NamedGroupList.tribes,
    name: 'Joseph',
    subtitle: "Jacob's eleventh son, by Rachel",
    notes:
        'Sold into slavery by his brothers, then rose to rule Egypt. His '
        'inheritance was later split between his two sons, Ephraim and '
        'Manasseh, keeping the tribal count at twelve without Levi.',
    citations: ['Genesis 30:24', 'Joshua 14:4'],
    order: 11,
  ),
  NamedGroupEntry(
    id: 'tribe-benjamin',
    list: NamedGroupList.tribes,
    name: 'Benjamin',
    subtitle: "Jacob's twelfth son, by Rachel — born in Canaan",
    notes: 'Rachel died giving birth to him; Saul, Israel\'s first king, was of this tribe.',
    citations: ['Genesis 35:18'],
    order: 12,
  ),

  // --- 12 Apostles (Matthew 10:2-4 order) ---
  NamedGroupEntry(
    id: 'apostle-peter',
    list: NamedGroupList.apostles,
    name: 'Simon Peter',
    subtitle: '"The Rock" — leader among the Twelve',
    notes: 'Denied Jesus three times the night of his arrest, then was restored and commissioned.',
    citations: ['Matthew 10:2', 'John 21:15-17'],
    order: 1,
  ),
  NamedGroupEntry(
    id: 'apostle-andrew',
    list: NamedGroupList.apostles,
    name: 'Andrew',
    subtitle: "Peter's brother, one of the first two disciples called",
    notes: 'Originally a disciple of John the Baptist before following Jesus.',
    citations: ['Matthew 10:2', 'John 1:40-42'],
    order: 2,
  ),
  NamedGroupEntry(
    id: 'apostle-james-zebedee',
    list: NamedGroupList.apostles,
    name: 'James (son of Zebedee)',
    subtitle: "John's brother, part of Jesus' inner circle",
    notes: 'The first apostle martyred, executed by Herod Agrippa I.',
    citations: ['Matthew 10:2', 'Acts 12:2'],
    order: 3,
  ),
  NamedGroupEntry(
    id: 'apostle-john',
    list: NamedGroupList.apostles,
    name: 'John',
    subtitle: '"The disciple whom Jesus loved"',
    notes: 'Traditionally credited with the Gospel of John, three epistles, and Revelation.',
    citations: ['Matthew 10:2', 'John 21:20'],
    order: 4,
  ),
  NamedGroupEntry(
    id: 'apostle-philip',
    list: NamedGroupList.apostles,
    name: 'Philip',
    subtitle: 'Brought Nathanael to Jesus',
    notes: 'From Bethsaida, the same town as Peter and Andrew.',
    citations: ['Matthew 10:3', 'John 1:45-46'],
    order: 5,
  ),
  NamedGroupEntry(
    id: 'apostle-bartholomew',
    list: NamedGroupList.apostles,
    name: 'Bartholomew (Nathanael)',
    subtitle: '"An Israelite indeed, in whom is no guile"',
    notes: 'Widely identified with the Nathanael of John\'s Gospel.',
    citations: ['Matthew 10:3', 'John 1:47'],
    order: 6,
  ),
  NamedGroupEntry(
    id: 'apostle-thomas',
    list: NamedGroupList.apostles,
    name: 'Thomas',
    subtitle: '"Doubting Thomas"',
    notes: 'Refused to believe the resurrection without physical proof, then confessed Jesus as Lord and God.',
    citations: ['Matthew 10:3', 'John 20:24-28'],
    order: 7,
  ),
  NamedGroupEntry(
    id: 'apostle-matthew',
    list: NamedGroupList.apostles,
    name: 'Matthew (Levi)',
    subtitle: 'Former tax collector',
    notes: 'Traditionally credited with the Gospel bearing his name.',
    citations: ['Matthew 10:3', 'Matthew 9:9'],
    order: 8,
  ),
  NamedGroupEntry(
    id: 'apostle-james-alphaeus',
    list: NamedGroupList.apostles,
    name: 'James (son of Alphaeus)',
    subtitle: 'Sometimes called "James the Less"',
    notes: 'Little is recorded of him beyond his name in the apostle lists.',
    citations: ['Matthew 10:3'],
    order: 9,
  ),
  NamedGroupEntry(
    id: 'apostle-thaddaeus',
    list: NamedGroupList.apostles,
    name: 'Thaddaeus (Judas son of James)',
    subtitle: 'Asked Jesus why he would reveal himself only to the disciples',
    notes: 'Distinguished by name from Judas Iscariot at the last supper.',
    citations: ['Matthew 10:3', 'John 14:22'],
    order: 10,
  ),
  NamedGroupEntry(
    id: 'apostle-simon-zealot',
    list: NamedGroupList.apostles,
    name: 'Simon the Zealot',
    subtitle: 'Named for a former political-nationalist allegiance',
    notes: 'His inclusion alongside Matthew (a tax collector) reflects the Twelve\'s political diversity.',
    citations: ['Matthew 10:4'],
    order: 11,
  ),
  NamedGroupEntry(
    id: 'apostle-judas-iscariot',
    list: NamedGroupList.apostles,
    name: 'Judas Iscariot',
    subtitle: 'Betrayed Jesus for thirty pieces of silver',
    notes: 'Kept the disciples\' money bag; hanged himself after the betrayal.',
    citations: ['Matthew 10:4', 'Matthew 26:14-16'],
    order: 12,
  ),

  // --- Judges of Israel (chronological order) ---
  NamedGroupEntry(
    id: 'judge-othniel',
    list: NamedGroupList.judges,
    name: 'Othniel',
    subtitle: 'Israel\'s first judge',
    notes: 'Delivered Israel from Cushan-rishathaim, king of Mesopotamia.',
    citations: ['Judges 3:9-11'],
    order: 1,
  ),
  NamedGroupEntry(
    id: 'judge-ehud',
    list: NamedGroupList.judges,
    name: 'Ehud',
    subtitle: 'A left-handed Benjamite',
    notes: 'Assassinated Eglon, king of Moab, with a concealed dagger.',
    citations: ['Judges 3:15-30'],
    order: 2,
  ),
  NamedGroupEntry(
    id: 'judge-shamgar',
    list: NamedGroupList.judges,
    name: 'Shamgar',
    subtitle: 'Struck down 600 Philistines with an ox goad',
    notes: 'Gets only a single verse, the briefest account of any judge.',
    citations: ['Judges 3:31'],
    order: 3,
  ),
  NamedGroupEntry(
    id: 'judge-deborah',
    list: NamedGroupList.judges,
    name: 'Deborah',
    subtitle: 'The only female judge, also a prophetess',
    notes: 'Led Israel to victory over Canaanite general Sisera and sang a victory song with Barak.',
    citations: ['Judges 4:4-5', 'Judges 5:1-3'],
    order: 4,
  ),
  NamedGroupEntry(
    id: 'judge-gideon',
    list: NamedGroupList.judges,
    name: 'Gideon',
    subtitle: 'Defeated Midian with just 300 men',
    notes: 'Tested God with the fleece before leading Israel\'s smallest army to a decisive victory.',
    citations: ['Judges 6:11-14', 'Judges 7:19-21'],
    order: 5,
  ),
  NamedGroupEntry(
    id: 'judge-tola',
    list: NamedGroupList.judges,
    name: 'Tola',
    subtitle: 'Judged Israel 23 years',
    notes: 'Little detail is recorded beyond his lineage and tenure.',
    citations: ['Judges 10:1-2'],
    order: 6,
  ),
  NamedGroupEntry(
    id: 'judge-jair',
    list: NamedGroupList.judges,
    name: 'Jair',
    subtitle: 'Had thirty sons who rode thirty donkeys',
    notes: 'A Gileadite who judged Israel 22 years.',
    citations: ['Judges 10:3-5'],
    order: 7,
  ),
  NamedGroupEntry(
    id: 'judge-jephthah',
    list: NamedGroupList.judges,
    name: 'Jephthah',
    subtitle: 'A rejected outcast turned military deliverer',
    notes: 'Defeated the Ammonites, but is remembered for a rash vow with tragic consequences for his daughter.',
    citations: ['Judges 11:1-3', 'Judges 12:7'],
    order: 8,
  ),
  NamedGroupEntry(
    id: 'judge-ibzan',
    list: NamedGroupList.judges,
    name: 'Ibzan',
    subtitle: 'Had thirty sons and thirty daughters',
    notes: 'Judged Israel from Bethlehem for seven years.',
    citations: ['Judges 12:8-10'],
    order: 9,
  ),
  NamedGroupEntry(
    id: 'judge-elon',
    list: NamedGroupList.judges,
    name: 'Elon',
    subtitle: 'A Zebulunite',
    notes: 'Judged Israel ten years; little else is recorded.',
    citations: ['Judges 12:11-12'],
    order: 10,
  ),
  NamedGroupEntry(
    id: 'judge-abdon',
    list: NamedGroupList.judges,
    name: 'Abdon',
    subtitle: 'Had forty sons and thirty grandsons who rode 70 donkeys',
    notes: 'The last of the "minor judges" before Samson.',
    citations: ['Judges 12:13-15'],
    order: 11,
  ),
  NamedGroupEntry(
    id: 'judge-samson',
    list: NamedGroupList.judges,
    name: 'Samson',
    subtitle: 'A Nazirite of superhuman strength',
    notes:
        'Betrayed by Delilah after revealing the secret of his strength; '
        'killed more Philistines in his death than in his life by pulling '
        'down their temple.',
    citations: ['Judges 13:24', 'Judges 16:28-30'],
    order: 12,
  ),
  NamedGroupEntry(
    id: 'judge-samuel',
    list: NamedGroupList.judges,
    name: 'Samuel',
    subtitle: 'Israel\'s last judge, also a prophet and priest',
    notes: 'Anointed Israel\'s first two kings, Saul and David, ending the era of the judges.',
    citations: ['1 Samuel 7:15-17'],
    order: 13,
  ),

  // --- Major & Minor Prophets (canonical order) ---
  NamedGroupEntry(
    id: 'prophet-isaiah',
    list: NamedGroupList.prophets,
    name: 'Isaiah',
    subtitle: 'Major Prophet, 8th century BC',
    notes: 'The most-quoted Old Testament prophet in the New Testament, including many Messianic prophecies.',
    citations: ['Isaiah 1:1'],
    order: 1,
  ),
  NamedGroupEntry(
    id: 'prophet-jeremiah',
    list: NamedGroupList.prophets,
    name: 'Jeremiah',
    subtitle: 'Major Prophet, 7th–6th century BC',
    notes: '"The weeping prophet," who ministered through Jerusalem\'s fall to Babylon.',
    citations: ['Jeremiah 1:1'],
    order: 2,
  ),
  NamedGroupEntry(
    id: 'prophet-ezekiel',
    list: NamedGroupList.prophets,
    name: 'Ezekiel',
    subtitle: 'Major Prophet, 6th century BC',
    notes: 'Prophesied among the exiles in Babylon, known for vivid visions like the valley of dry bones.',
    citations: ['Ezekiel 1:1'],
    order: 3,
  ),
  NamedGroupEntry(
    id: 'prophet-daniel',
    list: NamedGroupList.prophets,
    name: 'Daniel',
    subtitle: 'Major Prophet, 6th century BC',
    notes: 'Exiled to Babylon as a youth; served under multiple kings while receiving prophetic visions.',
    citations: ['Daniel 1:1'],
    order: 4,
  ),
  NamedGroupEntry(
    id: 'prophet-hosea',
    list: NamedGroupList.prophets,
    name: 'Hosea',
    subtitle: 'Minor Prophet, 8th century BC',
    notes: 'His troubled marriage to Gomer illustrated God\'s faithfulness to unfaithful Israel.',
    citations: ['Hosea 1:1'],
    order: 5,
  ),
  NamedGroupEntry(
    id: 'prophet-joel',
    list: NamedGroupList.prophets,
    name: 'Joel',
    subtitle: 'Minor Prophet, date debated',
    notes: 'A locust plague becomes the occasion for his call to repentance and promise of the Spirit poured out.',
    citations: ['Joel 1:1'],
    order: 6,
  ),
  NamedGroupEntry(
    id: 'prophet-amos',
    list: NamedGroupList.prophets,
    name: 'Amos',
    subtitle: 'Minor Prophet, 8th century BC',
    notes: 'A shepherd from Judah sent to confront the northern kingdom\'s social injustice.',
    citations: ['Amos 1:1'],
    order: 7,
  ),
  NamedGroupEntry(
    id: 'prophet-obadiah',
    list: NamedGroupList.prophets,
    name: 'Obadiah',
    subtitle: 'Minor Prophet — the shortest Old Testament book',
    notes: 'A single-chapter oracle of judgment against Edom.',
    citations: ['Obadiah 1:1'],
    order: 8,
  ),
  NamedGroupEntry(
    id: 'prophet-jonah',
    list: NamedGroupList.prophets,
    name: 'Jonah',
    subtitle: 'Minor Prophet, 8th century BC',
    notes: 'Fled his call to preach to Nineveh and was swallowed by a great fish before finally obeying.',
    citations: ['Jonah 1:1'],
    order: 9,
  ),
  NamedGroupEntry(
    id: 'prophet-micah',
    list: NamedGroupList.prophets,
    name: 'Micah',
    subtitle: 'Minor Prophet, 8th century BC',
    notes: 'Named Bethlehem as the Messiah\'s birthplace centuries in advance.',
    citations: ['Micah 1:1'],
    order: 10,
  ),
  NamedGroupEntry(
    id: 'prophet-nahum',
    list: NamedGroupList.prophets,
    name: 'Nahum',
    subtitle: 'Minor Prophet, 7th century BC',
    notes: 'Prophesied the destruction of Nineveh, over a century after Jonah\'s preaching there.',
    citations: ['Nahum 1:1'],
    order: 11,
  ),
  NamedGroupEntry(
    id: 'prophet-habakkuk',
    list: NamedGroupList.prophets,
    name: 'Habakkuk',
    subtitle: 'Minor Prophet, 7th century BC',
    notes: 'Structured as a dialogue with God over why the wicked prosper; "the just shall live by his faith."',
    citations: ['Habakkuk 1:1'],
    order: 12,
  ),
  NamedGroupEntry(
    id: 'prophet-zephaniah',
    list: NamedGroupList.prophets,
    name: 'Zephaniah',
    subtitle: 'Minor Prophet, 7th century BC',
    notes: 'Prophesied during Josiah\'s reign, warning of the coming "day of the LORD."',
    citations: ['Zephaniah 1:1'],
    order: 13,
  ),
  NamedGroupEntry(
    id: 'prophet-haggai',
    list: NamedGroupList.prophets,
    name: 'Haggai',
    subtitle: 'Minor Prophet, 6th century BC (post-exile)',
    notes: 'Urged the returned exiles to resume rebuilding the temple.',
    citations: ['Haggai 1:1'],
    order: 14,
  ),
  NamedGroupEntry(
    id: 'prophet-zechariah',
    list: NamedGroupList.prophets,
    name: 'Zechariah',
    subtitle: 'Minor Prophet, 6th century BC (post-exile)',
    notes: 'Ministered alongside Haggai, encouraging the temple\'s completion with vivid Messianic visions.',
    citations: ['Zechariah 1:1'],
    order: 15,
  ),
  NamedGroupEntry(
    id: 'prophet-malachi',
    list: NamedGroupList.prophets,
    name: 'Malachi',
    subtitle: 'Minor Prophet, 5th century BC — the last Old Testament book',
    notes: 'Closes the Old Testament rebuking Israel\'s complacency and looking ahead to a coming messenger.',
    citations: ['Malachi 1:1'],
    order: 16,
  ),
];
