import 'package:drift/drift.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../data/content_store.dart';
import '../data/importer/curated_topics_data.dart';
import '../data/importer/mybible_verse_parser.dart';
import '../data/user_store.dart';
import '../domain/explorer/explorer_ref.dart';
import '../domain/explorer/fuzzy_suggest.dart';
import '../domain/feasts/feast_data.dart' show feasts;
import '../domain/prophecy/prophecy_data.dart' show prophecies;
import '../domain/prophecy/prophecy_index.dart' show searchProphecies;
import '../domain/search/reference_parser.dart';
import 'content_providers.dart';
import 'document_reference_providers.dart';
import 'media_providers.dart';
import 'people_providers.dart';
import 'place_providers.dart';
import 'reader_state.dart';
import 'search_providers.dart';
import 'tag_providers.dart';
import 'topic_providers.dart';
import 'user_providers.dart';

part 'explorer_stats_providers.dart';
part 'explorer_browse_providers.dart';
part 'explorer_trail_providers.dart';
part 'explorer_search_providers.dart';
part 'explorer_event_detail_providers.dart';
part 'explorer_place_detail_providers.dart';
part 'explorer_person_detail_providers.dart';
part 'explorer_dictionary_providers.dart';
part 'explorer_verse_preview_providers.dart';
part 'explorer_passage_hit_providers.dart';
part 'explorer_topic_facet_providers.dart';
part 'explorer_tag_providers.dart';
